"""add compatibilities table

Revision ID: 321b481747dd
Revises: af835eadbb3d
Create Date: 2026-04-04 21:39:41.252387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '321b481747dd'
down_revision: Union[str, Sequence[str], None] = 'af835eadbb3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compatibilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id_1', sa.UUID(), nullable=False),
    sa.Column('profile_id_2', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id_1'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['profile_id_2'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id_1', 'profile_id_2', 'year', name='uq_compat_profiles_year')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('compatibilities')
    # ### end Alembic commands ###
