"""add_birth_hour_unknown_to_profiles

Revision ID: 8c34a7ac4f2a
Revises: fef0dae09176
Create Date: 2026-09-12 23:40:23.944588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c34a7ac4f2a'
down_revision: Union[str, Sequence[str], None] = 'fef0dae09176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 기존 행이 있으므로 server_default 필수 (is_self 마이그레이션과 동일 패턴)
    op.add_column('profiles', sa.Column('birth_hour_unknown', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'birth_hour_unknown')
    # ### end Alembic commands ###
