"""cascade_delete_compatibilities_fk

Revision ID: fbc0f370afd4
Revises: 43b9ae6c0441
Create Date: 2026-04-05 17:08:11.077748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc0f370afd4'
down_revision: Union[str, Sequence[str], None] = '43b9ae6c0441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('compatibilities_profile_id_1_fkey'), 'compatibilities', type_='foreignkey')
    op.drop_constraint(op.f('compatibilities_profile_id_2_fkey'), 'compatibilities', type_='foreignkey')
    op.create_foreign_key(None, 'compatibilities', 'profiles', ['profile_id_1'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'compatibilities', 'profiles', ['profile_id_2'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'compatibilities', type_='foreignkey')
    op.drop_constraint(None, 'compatibilities', type_='foreignkey')
    op.create_foreign_key(op.f('compatibilities_profile_id_2_fkey'), 'compatibilities', 'profiles', ['profile_id_2'], ['id'])
    op.create_foreign_key(op.f('compatibilities_profile_id_1_fkey'), 'compatibilities', 'profiles', ['profile_id_1'], ['id'])
    # ### end Alembic commands ###
